config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pets

  root 'pets#index'

  get 'search_events' => 'pets#search', as: 'search_events'

end

app/models/pet.rb
class Pet < ActiveRecord::Base

	searchkick language: ["English"]

	def filter_search(params)
		es_query = '*'
		attribute_filters = {
			where: {},
			order: {created_at: :asc},
			per_page: 5
		}

		self.search(es_query, attribute_filters)
	end

	def search_data
		{
			species: species,
			breed: breed,
			name: name,
			description: description
		}
	end

	belongs_to :user
	delegate :zip, to: :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :fname
    devise_parameter_sanitizer.for(:account_update) << :fname

    devise_parameter_sanitizer.for(:sign_up) << :lname
    devise_parameter_sanitizer.for(:account_update) << :lname

    devise_parameter_sanitizer.for(:sign_up) << :city
    devise_parameter_sanitizer.for(:account_update) << :city

    devise_parameter_sanitizer.for(:sign_up) << :state
    devise_parameter_sanitizer.for(:account_update) << :state

    devise_parameter_sanitizer.for(:sign_up) << :zip
    devise_parameter_sanitizer.for(:account_update) << :zip
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all

  end

  def search
      if params[:search].present?
        @pet = Pet.search(params[:search])
      else
        @pet = Pet.all
      end
  end

  # GET /pets/1
  # GET /pets/1.json
  def show

  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.user_id = current_user.id

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:species, :breed, :name, :age, :sex, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/_alert.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'Animal Site', root_path, class: "navbar-brand" %>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to 'About', '#' %></li>
      <li><%= link_to 'Contact', '#' %></l>
    </ul>
  </div>

<%= form_tag(search_events_path, {:method => 'get' , :class => "navbar-form navbar-left"}) do %>
  <div class = "form-group">
    <!-- names input and allows value survival through redirects and refresh-->
    <%= text_field_tag :search, params[:search], class: "form-control", autocomplete: "off"%>
    <!--keeps submit from showing up in URL query-->
    <%=submit_tag "Search", :name => nil, :class => "btn btn-default"%>
  </div>
<% end %>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">User Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Manage Listings", '#' %></li>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.fname %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnimalSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<div class="container">
		<%= render 'layouts/alert' %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :species %>
    <%= f.text_field :species, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :breed %>
    <%= f.text_field :breed, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :age %>
    <%= f.text_field :age, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :sex %>
    <%= f.text_field :sex, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', pets_path %>

app/views/pets/index.html.erb
<div class="jumbotron">
  <h1>Make a difference in an animal's life.</h1>
  <h2>Adopt a pet today!</h2>
</div>

<div class="row">
  <% @pets.each do |pet| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag("http://s3.amazonaws.com/kazijams/listings/images/000/000/001/original/shiba_inu_figure.jpg?1451007499"), pet %>
        <div class="caption">
          <h3><%= pet.name %></h3>
          <p>Breed: <%= pet.breed %></p>
          <p>Age: <%= pet.age %></p>
          <p>Sex: <%= pet.sex %></p>
          <p>Zip: <%= pet.zip %></p>
          <p><%= "Owned by #{pet.user.fname}" %></p>
          <% if current_user == pet.user %>
            <p><%= link_to 'Show', pet %></p>
            <p><%= link_to 'Edit', edit_pet_path(pet) %></p>
            <p><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Pet', new_pet_path %>
<% end %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', pets_path %>

app/views/pets/search.html.erb
<div class="row">
  <% @pet.each do |pet| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag("http://s3.amazonaws.com/kazijams/listings/images/000/000/001/original/shiba_inu_figure.jpg?1451007499"), pet %>
        <div class="caption">
          <h3><%= pet.name %></h3>
          <p>Breed: <%= pet.breed %></p>
          <p>Age: <%= pet.age %></p>
          <p>Sex: <%= pet.sex %></p>
          <p><%= "Owned by #{pet.user.fname}" %></p>
          <% if current_user == pet.user %>
            <p><%= link_to 'Show', pet %></p>
            <p><%= link_to 'Edit', edit_pet_path(pet) %></p>
            <p><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Pet', new_pet_path %>
<% end %>

app/views/pets/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag("http://s3.amazonaws.com/kazijams/listings/images/000/000/001/original/shiba_inu_figure.jpg?1451007499") %>
    </div>
  </div>
  <div class="col-md-6">
    <h3><%= @pet.name %></h3>
    <p><strong>Species:</strong> <%= @pet.species %></p>
    <p><strong>Breed:</strong> <%= @pet.breed %></p>
    <p><strong>Age:</strong> <%= @pet.age %></p>
    <p><strong>Sex:</strong> <%= @pet.sex %></p>
    <p><strong>Owner:</strong> <%= @pet.user.fname %></p>
    <p><%= @pet.description %></p>
    <br>

  </div>
</div>

<% if current_user == @pet.user %>
  <%= link_to 'Edit', edit_pet_path(@pet) %> |
<% end %>
<%= link_to 'Back', pets_path %>